name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Project Checkout
                uses: actions/checkout@v2

            -   name: Setup JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: '11'

            -   name: System Information         
                run: printf "\nKernel:\n " && uname -a && printf "\n\nMemory:\n " && free -h && printf "\n\nStorage:\n" && df -h && ls -la && pwd

            -   name: Run tests
                run: ./gradlew test --stacktrace # testDebug or testRelease (if you have any)

            -   name: Unit tests results
                uses: actions/upload-artifact@v3
                with:
                    name: test-report
                    path: catch-android-sdk/build/reports/tests/testDebugUnitTest/

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            -   name: Project Checkout
                uses: actions/checkout@v2

            -   name: Setup JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: '11'

            -   name: System Information         
                run: printf "\nKernel:\n " && uname -a && printf "\n\nMemory:\n " && free -h && printf "\n\nStorage:\n" && df -h && ls -la && pwd

            -   name: Lint
                run: ./gradlew lint --stacktrace

            -   name: Lint results
                uses: actions/upload-artifact@v3
                with:
                    name: lint-report
                    path: catch-android-sdk/build/reports/lint-results-debug.html

    detekt:
        name: Detekt
        runs-on: ubuntu-latest

        steps:
            -   name: Project Checkout
                uses: actions/checkout@v2

            -   name: Setup JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: '11'

            -   name: System Information
                run: printf "\nKernel:\n " && uname -a && printf "\n\nMemory:\n " && free -h && printf "\n\nStorage:\n" && df -h && ls -la && pwd

            -   name: Run Detekt
                run: ./gradlew detekt --stacktrace

            -   name: Detekt results
                uses: actions/upload-artifact@v3
                with:
                    name: detekt-reports
                    path: |
                        catch-android-sdk/build/reports/detekt/detekt.html
                        sample/build/reports/detekt/detekt.html
